//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfileSPA.TestCases.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class COA_SP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal COA_SP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserProfileSPA.TestCases.Resource.COA_SP", typeof(COA_SP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no fare alerts..
        /// </summary>
        internal static string CommentFTinOverViewpage {
            get {
                return ResourceManager.GetString("CommentFTinOverViewpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no upcoming trips scheduled..
        /// </summary>
        internal static string CommentUTinOverviewPage {
            get {
                return ResourceManager.GetString("CommentUTinOverviewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recent searches..
        /// </summary>
        internal static string CommrntRSinOverViewpage {
            get {
                return ResourceManager.GetString("CommrntRSinOverViewpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your password,Both passwords do not match.
        /// </summary>
        internal static string confrmpassworderror {
            get {
                return ResourceManager.GetString("confrmpassworderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Fare Alert.
        /// </summary>
        internal static string CreateFareAlerFTbtn {
            get {
                return ResourceManager.GetString("CreateFareAlerFTbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both passwords do not match.
        /// </summary>
        internal static string ecpectedWhenBothNotSame {
            get {
                return ResourceManager.GetString("ecpectedWhenBothNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact phone is missing.
        /// </summary>
        internal static string errorContactNomissing {
            get {
                return ResourceManager.GetString("errorContactNomissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid contact phone,Contact phone is missing.
        /// </summary>
        internal static string errorMsgForContact {
            get {
                return ResourceManager.GetString("errorMsgForContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mobile phone.
        /// </summary>
        internal static string errorMsgForMobile {
            get {
                return ResourceManager.GetString("errorMsgForMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string expectedEmailErrorWhenBlank {
            get {
                return ResourceManager.GetString("expectedEmailErrorWhenBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string expectedEmailErrorWhenWrong {
            get {
                return ResourceManager.GetString("expectedEmailErrorWhenWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password.
        /// </summary>
        internal static string expectedPasswordErrorWhenBlank {
            get {
                return ResourceManager.GetString("expectedPasswordErrorWhenBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email or password has not been found.
        ///Lets get you back on track to the fastest way
        ///to book your flight.
        ///Already have an account?
        ///Try re-entering your email address and password.
        ///Forgot your password?
        ///Let us know and we’ll email it to you.
        ///New to the site?
        ///Click here to create an account – its quick &amp; easy..
        /// </summary>
        internal static string expectedPasswordNotMatchingValidationError {
            get {
                return ResourceManager.GetString("expectedPasswordNotMatchingValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your Gender.
        /// </summary>
        internal static string expectedValidationInCotravelerGender {
            get {
                return ResourceManager.GetString("expectedValidationInCotravelerGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Title.
        /// </summary>
        internal static string expectedValidationInCoTravelerTitle {
            get {
                return ResourceManager.GetString("expectedValidationInCoTravelerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is required,Please enter a password,Please confirm your password,Please enter first name,Please enter last name,Please provide a date of birth,Please select the Gender.
        /// </summary>
        internal static string expectedValidationsIfCreateMyAccountIsEmpty {
            get {
                return ResourceManager.GetString("expectedValidationsIfCreateMyAccountIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is required.,Not a valid expiry date,Please enter first name,Please enter last name,Card Nick Name is required.,Address Line1 is required.,City is required.,Please enter zip code,Please enter billing phone..
        /// </summary>
        internal static string expectedValidationsIfMyBillingDetailsIsEmpty {
            get {
                return ResourceManager.GetString("expectedValidationsIfMyBillingDetailsIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name,Please enter last name.
        /// </summary>
        internal static string expectedValidationsIfMyCoTravelerIsNameFieldIsEmpty {
            get {
                return ResourceManager.GetString("expectedValidationsIfMyCoTravelerIsNameFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select proper title.Please enter street details.City name missing.Please enter zip code.Contact phone is missing.
        /// </summary>
        internal static string expectedValidationsIfMyInfoisEmpty {
            get {
                return ResourceManager.GetString("expectedValidationsIfMyInfoisEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Month,Please select Date,Please select Year.
        /// </summary>
        internal static string expectedValidationsInDobDropDownWhileAddingCoTraveler {
            get {
                return ResourceManager.GetString("expectedValidationsInDobDropDownWhileAddingCoTraveler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a date of birth.
        /// </summary>
        internal static string expectedValidationsInDObWhileCreateAnAccountIsEmpty {
            get {
                return ResourceManager.GetString("expectedValidationsInDObWhileCreateAnAccountIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Gender.
        /// </summary>
        internal static string expectedValidationsInSelectGenderWhileCreateAnAccountIsEmpty {
            get {
                return ResourceManager.GetString("expectedValidationsInSelectGenderWhileCreateAnAccountIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name missing,Please enter your state.
        /// </summary>
        internal static string expectedValidationsOfCityAndState {
            get {
                return ResourceManager.GetString("expectedValidationsOfCityAndState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be 5-32 characters.
        /// </summary>
        internal static string expectedWhenBothLengthNotExpected {
            get {
                return ResourceManager.GetString("expectedWhenBothLengthNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email entered is already associated with an account..
        /// </summary>
        internal static string expectedWhenEmailIsAlreadyExist {
            get {
                return ResourceManager.GetString("expectedWhenEmailIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is required.
        /// </summary>
        internal static string expectedWhenEmailIsEmpty {
            get {
                return ResourceManager.GetString("expectedWhenEmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address..
        /// </summary>
        internal static string ForgetPasswordValidation {
            get {
                return ResourceManager.GetString("ForgetPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a password between 5-32 characters.
        /// </summary>
        internal static string newpassworderror {
            get {
                return ResourceManager.GetString("newpassworderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no fare alerts..
        /// </summary>
        internal static string NoFares {
            get {
                return ResourceManager.GetString("NoFares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Search Now.
        /// </summary>
        internal static string StartSearchNowBtnRS {
            get {
                return ResourceManager.GetString("StartSearchNowBtnRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Search Now.
        /// </summary>
        internal static string StartSearchNowUT {
            get {
                return ResourceManager.GetString("StartSearchNowUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select,Mstr,Miss.
        /// </summary>
        internal static string titleForChildAndInfant {
            get {
                return ResourceManager.GetString("titleForChildAndInfant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select,Mr,Mrs,Miss,Ms,Dr,Rev.
        /// </summary>
        internal static string titlesForAdultAndSenior {
            get {
                return ResourceManager.GetString("titlesForAdultAndSenior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions,Airline Telephone Numbers,Online Flight Check-in,Visa &amp; Passport,Currency Converter,See all Travel Tools.
        /// </summary>
        internal static string TravelTools {
            get {
                return ResourceManager.GetString("TravelTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Information Has Been Updated..
        /// </summary>
        internal static string UpdateStatus {
            get {
                return ResourceManager.GetString("UpdateStatus", resourceCulture);
            }
        }
    }
}
